### ISSUE TITLE
ccc

### ISSUE THREAD

**Issue by benjamincanac** [cmty-test/test#94]
### What problem does this feature solve?

ccc

<div align="right"><sub><em>This question is available on <a href="http://terrajs.cmty.localhost">Terra JS</a> community (<a href="http://terrajs.cmty.localhost/cmty-test/test/issues/c1397">#c1397</a>)</em></sub></div>

**Comment by benjamincanac** [comment]
aaa

**Comment by gaetansenn** [comment]
I should watch by default now !
